apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://monitoring-prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://monitoring-jaeger:16686
    uid: jaeger
    editable: true
